In [34]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [35]:
data = {
    'Age': [25, 30, 35, np.nan, 28, 40, 32],
    'Salary': [50000, 60000, 65000, 70000, np.nan, 80000, 62000],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Purchased': ['Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)

In [36]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Age          1
Salary       1
Gender       0
Purchased    0
dtype: int64


In [37]:
print("Duplicate Rows:")
print(df.duplicated().sum())

Duplicate Rows:
0


In [38]:
df = df.drop_duplicates()

In [39]:
print("Original Dataset:")
print(df)

Original Dataset:
    Age   Salary  Gender Purchased
0  25.0  50000.0    Male       Yes
1  30.0  60000.0  Female        No
2  35.0  65000.0  Female       Yes
3   NaN  70000.0    Male        No
4  28.0      NaN  Female       Yes
5  40.0  80000.0    Male        No
6  32.0  62000.0  Female       Yes


In [40]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

print("Dataset after handling missing values:")
print(df)

Dataset after handling missing values:
         Age   Salary  Gender Purchased
0  25.000000  50000.0    Male       Yes
1  30.000000  60000.0  Female        No
2  35.000000  65000.0  Female       Yes
3  31.666667  70000.0    Male        No
4  28.000000  64500.0  Female       Yes
5  40.000000  80000.0    Male        No
6  32.000000  62000.0  Female       Yes


In [41]:
le_gender = LabelEncoder()
df['Gender'] = le_gender.fit_transform(df['Gender'])

In [42]:
le_purchased = LabelEncoder()
df['Purchased'] = le_purchased.fit_transform(df['Purchased'])

In [43]:
print("Dataset after handling missing values and encoding:")
print(df)

Dataset after handling missing values and encoding:
         Age   Salary  Gender  Purchased
0  25.000000  50000.0       1          1
1  30.000000  60000.0       0          0
2  35.000000  65000.0       0          1
3  31.666667  70000.0       1          0
4  28.000000  64500.0       0          1
5  40.000000  80000.0       1          0
6  32.000000  62000.0       0          1


In [44]:
X = df[['Age', 'Salary', 'Gender']]
y = df['Purchased']

In [45]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [46]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [47]:
print("Scaled Training Features:")
print(X_train)

Scaled Training Features:
[[ 1.66435666  1.828125    1.22474487]
 [ 0.41608917 -0.515625   -0.81649658]
 [-1.33148533 -0.59375    -0.81649658]
 [-0.41608917  0.265625    1.22474487]
 [-0.33287133 -0.984375   -0.81649658]]


In [48]:
print("Scaled Testing Features:")
print(X_test)

Scaled Testing Features:
[[-2.08044583 -2.859375    1.22474487]
 [-0.83217833 -1.296875   -0.81649658]]


In [49]:
print("Final Preprocessed Dataset:")
print(df)

print("\nFinal Missing Values:")
print(df.isnull().sum())

print("\nFinal Duplicate Rows:")
print(df.duplicated().sum())

Final Preprocessed Dataset:
         Age   Salary  Gender  Purchased
0  25.000000  50000.0       1          1
1  30.000000  60000.0       0          0
2  35.000000  65000.0       0          1
3  31.666667  70000.0       1          0
4  28.000000  64500.0       0          1
5  40.000000  80000.0       1          0
6  32.000000  62000.0       0          1

Final Missing Values:
Age          0
Salary       0
Gender       0
Purchased    0
dtype: int64

Final Duplicate Rows:
0
